import type { Obstacle } from './types'

export const obstacles: Obstacle[] = [
    {
        id: 'raid-250',
        name: '250 бб лох',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: '18plus',
        name: '18+',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'aloekoala-official',
        name: 'AloeKoala Official',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'pr-beggar',
        name: 'PR попрошайка',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'tier-d',
        name: 'Tier D',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'australian-hearthstone',
        name: 'Австралийский Hearthstone',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'anime',
        name: 'АНИМЭЭЭЭ',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'hello-dont-be-silent',
        name: 'Алло, не молчи',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'armageddon',
        name: 'Армагеддон',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'auf',
        name: 'Ауф',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dota-player',
        name: 'Ахаха, ты что, дотер?',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'granny-swears',
        name: 'Бабка-матершинница',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'biba-boba',
        name: 'Биба и Боба',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'goddess',
        name: 'Богиня',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'shadow-fight',
        name: 'Бой с тенью',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'bombardment',
        name: 'Бомбардировка',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'bullying',
        name: 'Буллинг',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'vanga',
        name: 'Ванга',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'female-bath-day',
        name: 'В бане женский день',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'male-bath-day',
        name: 'В бане мужской день',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'enter-coordinates',
        name: 'Введите координаты',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'weight-control',
        name: 'Весовой контроль',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'fortune-telling',
        name: 'Ворожба',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'what-a-fight',
        name: 'Вот это замес!',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'time-loop',
        name: 'Временная петля',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'no-choice',
        name: 'Выбор без выбора',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'auction-main-lot',
        name: 'Главный лот аукциона',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'naked-run',
        name: 'Голый забег',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'grinch',
        name: 'Гринч',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'wardrobe-crush',
        name: 'Давка в гардеробе',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'give-me-that',
        name: 'Дайте мне вон то',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'coin-rain',
        name: 'Дождь из монет',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'fucking-casino',
        name: 'Ебанный рот этого казино!',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'hot-or-cold',
        name: 'Жарко или холодно?',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'press-it',
        name: 'Жми, екарный бабай!',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'forgot-safeword',
        name: 'Забыла стоп слово',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'got-viral',
        name: 'Завирусился',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'slowdown',
        name: 'Замедлятор',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'star-troopers',
        name: 'Звездный десант',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sound-engineer',
        name: 'Звукорежиссер',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'play-on-increase',
        name: 'Игра на повышение',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'play-on-decrease',
        name: 'Игра на понижение',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'import-substitution',
        name: 'Импортозамещение',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'stone-i-give',
        name: 'Камень я дам',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'catapult',
        name: 'Катапульта',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'game-for-cheaters',
        name: 'Катка для челипиздриков',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'cyberpunk',
        name: 'Киберпук',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'kinopoisk',
        name: 'Кинопоиск',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'throw-cow-or-food',
        name: 'Кинь коровку или харчок',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'whip-and-candy',
        name: 'Кнут и пряник',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'code-green',
        name: 'Код Зеленый',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'code-red',
        name: 'Код Красный',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'reusability-wheel',
        name: 'Колесо многоразовости',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'one-time-wheel',
        name: 'Колесо одноразовости',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'beauty-contest',
        name: 'Конкурс красоты',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'king-and-jester',
        name: 'Король и шут',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'wallet-or-life',
        name: 'Кошелек или жизнь',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'spin-the-drum',
        name: 'Крутите барабан',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'where-without-hymn',
        name: 'Куда мы без гимна',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'aliexpress-coupon',
        name: 'Купон с Алиэкспресса',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'picasso-lasso',
        name: 'Лассо Пикассо',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'ice-rain',
        name: 'Ледяной дождь',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sticky-place',
        name: 'Липкое место',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'bald-dick',
        name: 'Лысый хер',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'lyas-mas',
        name: 'Ляськи Масяськи',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'mimic',
        name: 'Мимик',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'minefield',
        name: 'Минное поле',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'maybe-deal',
        name: 'Может, договоримся?',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'jukebox',
        name: 'Музыкальный автомат',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'meow-content',
        name: 'Мяу контент',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'vat',
        name: 'НДС',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'air-tax',
        name: 'Налог на воздух',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'found-gigolo',
        name: 'Нашла себе альфонса',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dont-step-in-cow-poop',
        name: 'Не наступи в коровью лепешку!',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dont-look-at-welding',
        name: 'Не смотри на сварку',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dont-touch-new-year',
        name: 'Не трогай - это на новый год',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'body-swap',
        name: 'Обмен телами',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'oops-stash',
        name: 'Опа, закладка',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'special-obstacle',
        name: 'Особо важная помеха',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'unwind',
        name: 'Открутка',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sausage-fingers',
        name: 'Пальцы-сосиски',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'jurassic-park',
        name: 'Парк юрского периода',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'flip-2',
        name: 'Перевертыш 2.0',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'baikit-census',
        name: 'Перепись населения в Байките',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'perforator',
        name: 'Перфоратор',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'wrong-turn',
        name: 'Поворот не туда',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'tweak',
        name: 'Подкрутка',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'chat-trick',
        name: 'Подлянка от чата',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'search-balloon',
        name: 'Поисковый аэростат',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'show-your-carrot',
        name: 'Покажи свою морковку',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'night-owl',
        name: 'Полуночник',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'diarrhea-curse',
        name: 'Порча на понос',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'suck-it',
        name: 'Пососи дуло',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'predictions-2025',
        name: 'Предсказания на 2025',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'pension-bonus',
        name: 'Прибавка к пенсии',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'goy-heating',
        name: 'Прогрев гоев',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'cursed-artifact',
        name: 'Проклятый артефакт',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'curse',
        name: 'Проклятье',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'skip-fillers',
        name: 'Проматываем филлеры',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'professional-card-player',
        name: 'Профессиональная картежница',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'change-coin',
        name: 'Разменная монета',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'size-doesnt-matter',
        name: 'Размер не важен',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'randomizer',
        name: 'Рандомайзер',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'relocant',
        name: 'Релокант',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'restaurant-critics',
        name: 'Ресторанные критики',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'slingshot-copy',
        name: 'Рогатка-копирка',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'midas-hand',
        name: 'Рука Мидаса',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sasai-kudasai',
        name: 'Сасай Кудасай',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'silent-hill',
        name: 'Сайлент Хилл',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sound-producer',
        name: 'Саунд-продюсер',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'energy-drink-day',
        name: 'С днем энергетика!',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'burn-the-witch',
        name: 'Сжечь ведьму!',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'scouts',
        name: 'Скауты',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'skibidi-toilet',
        name: 'Скибиди туалет',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'slippery-type',
        name: 'Скользкий тип',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'how-many-pts',
        name: 'Сколько птс?',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'rapid-fire',
        name: 'Скорострел',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'scoff-patrol',
        name: 'Скуф патруль',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sweet-koaleland',
        name: 'Сладкое коалевство',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'tear-gas',
        name: 'Слезоточивый газ',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'watched-on-cinema',
        name: 'Смотрели на киноауке',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'toilet-flush',
        name: 'Смыв унитаза',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'dog-lady',
        name: 'Собачница',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'doubtful-hobby',
        name: 'Сомнительное хобби',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'bet-chat',
        name: 'Ставка, чат!',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'stop-inflation',
        name: 'Стоп инфляция',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'boner',
        name: 'Стояк',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'tarantino-stream',
        name: 'Стрим для Тарантино',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'supervillain',
        name: 'Суперзлодей',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'solid-chair',
        name: 'Твердый стул',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'teleport',
        name: 'Телепорт',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'tili-tili-dough',
        name: 'Тили-тили тесто',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'you-sat-on-stump',
        name: 'Ты на пенек сел - должен был косарь отдать',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'you-shall-not-pass',
        name: 'Ты не пройдешь!!!',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'taser-hit',
        name: 'Удар шокером',
        type: 'событие',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'fuckshit',
        name: 'Факшит',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'friendly-strip-lobby',
        name: 'Френдли лобби на раздевание',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'cant-remember',
        name: 'Хоть убей не помню',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'china-number-one',
        name: 'Чайна намбер ван!!!',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'chat-gpt',
        name: 'Чат GPT',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'chat-is-law',
        name: 'Чат здесь закон',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'black-hole',
        name: 'Черная дыра',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'devils-dozen',
        name: 'Чертова дюжина',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'chin-chin-chirin',
        name: 'Чин-чин-чиринь',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'cheater-wheel',
        name: 'Читерское колесо',
        type: 'многоразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'sheikhs-decide',
        name: 'Шейхи решают вопросики',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'epidemic',
        name: 'Эпидемия',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'what-pokemon',
        name: 'Это что за покемон',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'im-russian',
        name: 'Я РУССКИЙ',
        type: 'одноразовая',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'im-tired-im-leaving',
        name: 'Я устал. Я ухожу.',
        type: 'один раз за стрим',
        description: null,
        isUnlocked: false,
        isActive: false,
        updatedAt: new Date().toISOString(),
    },
]
