import type { Follower } from '../../model/follower'

export function getAllFollowers(): Follower[] {
    return [
        {
            id: 1,
            name: 'Zhrun1',
            helpSpins: 21,
            interferenceSpins: 16,
            contribution: 31289,
        },
        {
            id: 2,
            name: 'Best_try',
            helpSpins: 11,
            interferenceSpins: 11,
            contribution: 18000,
        },
        {
            id: 3,
            name: 'PastGenKnight',
            helpSpins: 19,
            interferenceSpins: 1,
            contribution: 14777,
        },
        {
            id: 4,
            name: 'Daddypancake',
            helpSpins: 7,
            interferenceSpins: 4,
            contribution: 14488,
        },
        {
            id: 5,
            name: 'Lord_cthulhu_23',
            helpSpins: 12,
            interferenceSpins: 0,
            contribution: 12304,
        },
        {
            id: 6,
            name: 'RV',
            helpSpins: 0,
            interferenceSpins: 14,
            contribution: 11665,
        },
        {
            id: 7,
            name: '0706aestyles',
            helpSpins: 7,
            interferenceSpins: 0,
            contribution: 8640,
        },
        {
            id: 8,
            name: 'Dimaps',
            helpSpins: 1,
            interferenceSpins: 0,
            contribution: 2000,
        },
        {
            id: 9,
            name: 'Азазелочка',
            helpSpins: 0,
            interferenceSpins: 0,
            contribution: 1514,
        },
        {
            id: 10,
            name: 'Zheshua',
            helpSpins: 0,
            interferenceSpins: 0,
            contribution: 1000,
        },
        {
            id: 11,
            name: 'H_a_l_k_a_r',
            helpSpins: 1,
            interferenceSpins: 0,
            contribution: 785,
        },
        {
            id: 12,
            name: 'Miror842',
            helpSpins: 0,
            interferenceSpins: 1,
            contribution: 777,
        },
        {
            id: 13,
            name: 'Коломбина',
            helpSpins: 0,
            interferenceSpins: 1,
            contribution: 777,
        },
        {
            id: 14,
            name: 'Сатурн',
            helpSpins: 0,
            interferenceSpins: 1,
            contribution: 777,
        },
        {
            id: 15,
            name: 'Broadvvey',
            helpSpins: 1,
            interferenceSpins: 0,
            contribution: 350,
        },
        {
            id: 16,
            name: 'Lisichka',
            helpSpins: 0,
            interferenceSpins: 0,
            contribution: 219,
        },
        {
            id: 17,
            name: 'mashmet19',
            helpSpins: 0,
            interferenceSpins: 0,
            contribution: 200,
        },
        {
            id: 18,
            name: 'Kolovrate',
            helpSpins: 0,
            interferenceSpins: 0,
            contribution: 150,
        },
        {
            id: 19,
            name: 'PanicAtTheZu',
            helpSpins: 0,
            interferenceSpins: 0,
            contribution: 136,
        },
    ]
}
